### ISSUE TITLE
Break the loop after a timeout

### ISSUE THREAD

**Issue by danstarns** [danstarns/for-emit-of#1]
# Example
```javascript
const iterator = forEmitOf(readStream, {
    timeout: 1000, // ms
});

for await (const chunk of iterator) {
    console.log(chunk);
}
```
After 1000ms iterator will break.

**Comment by Farenheith** [comment]
I want to contribute with this one!
How do you want it to behave?
Did you though that the iterator should just end or it should throw an error if the timeout is reached?

**Comment by Farenheith** [comment]
I just made a PR that throws an error if the timeout is reached. I hope that's what you was expecting :)
